# Generated by Django 3.1.12 on 2021-11-27 06:26

import autoslug.fields
import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view', models.IntegerField(default=1, verbose_name="Ko'rilganlar")),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Nomi (rus tilida)')),
                ('meta_desc', models.CharField(blank=True, db_index=True, max_length=255, verbose_name="Mazmuni (o'zbek tilida)")),
                ('meta_key', models.CharField(blank=True, db_index=True, max_length=255, verbose_name="Kalit so'zlari (o'zbek tilida)")),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(db_index=True, max_length=50000, verbose_name='Maqola (rus tilida)')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Tahrirlangan vaqti')),
                ('slug', autoslug.fields.AutoSlugField()),
                ('sort', models.IntegerField(blank=True, null=True, verbose_name='Tartiblash')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Muallif')),
            ],
            options={
                'verbose_name': 'Maqola',
                'verbose_name_plural': 'Maqolalar',
            },
        ),
        migrations.CreateModel(
            name='HelpSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name="Nomi (o'zbek tilida)")),
                ('meta_desc', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Mazmuni (rus tilida)')),
                ('meta_key', models.CharField(blank=True, db_index=True, max_length=255, verbose_name="Kalit so'zlari (rus tilida)")),
                ('slug', autoslug.fields.AutoSlugField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('sort', models.IntegerField(blank=True, null=True, verbose_name='Tartiblash')),
            ],
            options={
                'verbose_name': "Bo'lim",
                'verbose_name_plural': "Bo'limlar",
            },
        ),
        migrations.CreateModel(
            name='Helpful',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='Ip manzil')),
                ('status', models.BooleanField(default=False, verbose_name='Holati')),
                ('help_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='help.helparticle', verbose_name='Maqola')),
            ],
            options={
                'verbose_name': 'Baho',
                'verbose_name_plural': 'Baholar',
            },
        ),
        migrations.AddField(
            model_name='helparticle',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='help.helpsection', verbose_name="Bo'lim"),
        ),
    ]
